### ISSUE TITLE
Allow showing track number without track total and zero padding

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#1192]
Original [issue 1291](https://code.google.com/p/ddb/issues/detail?id=1291) created by Alexey-Yakovenko on 2015-03-12T19:11:16.000Z:

Minor request, currently both %track% and %track number% show the numbers in the format of &quot;track/total&quot; and there doesn't seem a way to change that. I'd rather have one of them show only the track number. 

Basically:
- %track% should show 1/19 (as it does now)
- %track number% -&gt; 01 (as per fb2k tf, this currently works as %track%)
- %tracknumber% -&gt; 1 (as per fb2k tf, this is currently missing)

Maybe also add something like %track total% which only shows total tracks in the album.

**Comment by Soukyuu** [comment]
I just tested, and it seems to be ffmpeg-specific. Or rather, the way ffmpeg reads APEv2 tags in .tak. 

For other formats, it is as follows:
- `%track%` shows 1
- `%track number%` shows 1 (instead of 01 as per fb2k tf)
- `%tracknumber%` shows 01 (instead of 1 as per fb2k tf)

So at the moment, `%track number%` and `%tracknumber%` behavior is swapped if we are to follow fb2k and .tak itself needs additional parsing to split up the 1/19 in `%tracknumber%` and `%tracktotal%`

The splitting up has to be done for `%discnumber%`/`%disctotal%` as well, btw.

**Comment by Alexey-Yakovenko** [comment]
You read the specification wrong. According to FB2K reference, the %tracknumber% is the one with zero-padding.

This makes the bug invalid.
I will make another ticket for ffmpeg tracknumber splitting.
