### ISSUE TITLE
Non-square covers not properly displayed (bad quality).

### ISSUE THREAD

**Issue by Soukyuu** [Alexey-Yakovenko/deadbeef#1200]
There seems to be a problem with covers that are not square, the resize result looks as if it was resized with nearest neighbor. Even at (close to) 100%, the image quality is really bad.

Here is an [example cover](https://cloud.githubusercontent.com/assets/2095054/6804477/2ac10568-d23e-11e4-9a16-d3965bb5bf43.jpg), and here is how it [looks in ddb](https://cloud.githubusercontent.com/assets/2095054/6804579/bd90dcec-d23e-11e4-8a96-cc5061c227eb.png) 
(Note: the displacement to the right is due to screenshot cutting).

If I match the panel aspect ratio to cover aspect ratio, the cover looks correct, but the square ones do not. It seems that the album art panel uses the aspect ratio or the panel for the resize, not the aspect ratio of the image itself.

deadbeef-git, arch x64

**Comment by Alexey-Yakovenko** [comment]
Are you talking about cover art widget, or the playlist (album art column), or OSD notification, or all of them?

**Comment by Soukyuu** [comment]
The widget, but now that I looked at the column, it does the same thing as well.
The OSD is affected as well, it doesn't even keep the aspect ratio (rectangular -> stretched to square). I'm on KDE4 if it matters.

**Comment by Alexey-Yakovenko** [comment]
most likely it's kde4's fault for not maintaining the aspect ratio in OSD.
everything else is somewhere in deadbeef code for sure...

**Comment by Alexey-Yakovenko** [comment]
While you're at it -- could you verify if the same thing happens with last stable release 0.6.2?
(you will need to delete the ~/.cache/deadbeef folder before running it)

**Comment by Soukyuu** [comment]
Yes, 0.6.2-3 from the official repos shows the same behavior.

**Comment by Soukyuu** [comment]
The files themselves are correctly extracted to the ./cache/deadbeef/covers folder by the way.

**Comment by Lithopsian** [comment]
The resizing may be done by Deadbeef, or by an external library, depending on the build configuration.  If imlib is present, then it will be used for resizing, and quality should be decent.  Without imlib, resizing is done by Deadbeef code and it used to be poor.  I added code to do it better, not sure if it is in 0.6.2 but should be in trunk.

The OSD thumbnail size can be set in the preferences.  If the system OSD icon size is different then the OSD library will resize again, and that is probably causing your troubles.  Might be an enhancement to have Deadbeef always a supply a square icon?

The widget will be scaled from the cache file to the screen by a GDK function.  Quality should be good, but maybe there is an issue somewhere there?  I haven't see any problems, so maybe depends on GTK version?  Resizing the widget is done using a quick'n'dirty quality, and then redrawn at high quality after the resizing.  Could this be failing and leaving the poor quality version?  Do you only see the image quality issue with non-square covers?

**Comment by Soukyuu** [comment]
imlib2 is installed according to pacman, so that shouldn't be it. 

The OSD should be always supplied with a square image, I guess. I don't know which file format it uses, but you could "letterbox" the cover to reach the square ratio, either filling the sides with a color, or just keep them transparent. Another possibility would be cutting the cover to reach the square ratio. At the moment it's just being stretched by the OSD, I'm guessing.

I'm not sure it depends on the GTK version, my current one is 2.24.28. And yes, only non-square covers suffer from the issue.

**Comment by Lithopsian** [comment]
I have reproduced the problem here and I know why it is happening.  The cached file is OK.  It gets loaded and scaled into a pixbuf and that is OK.  Then that gets resized by cairo to fit the widget.  For square images, the pixbuf exactly matches the widget size, cairo does nothing, and the artwork looks good.  When the image is non-square, an unnecessary scaling is being done and this blurs the image.

I've already made some changes to this which I don't think made it to the 0.6.2 release, but even they don't eliminate the problem.  The scaling calculation for the pixbuf isn't correct for non-square images and the cairo_scale still happens and sort of hides the error, except that the image gets slightly blurred.

**Comment by Soukyuu** [comment]
Well, I'm on a git snapshot, and while it gets blurry, it is also still heavily aliased.

**Comment by Lithopsian** [comment]
The cairo filter is set for speed, not quality.  It is there to enable the widget to be resized in real time.  Then when the resizing is done (or just if you hesitate!) the entire pixbuf is re-generated using a high quality algorithm.  You are seeing a pixbuf that got built to the wrong size, then "fixed" to the correct size by cairo, but using a low quality algorithm (similar to, but not exactly, nearest neighbour).  I think the fix is easy, just have to play around some to be certain it doesn't mess up.

**Comment by Lithopsian** [comment]
Turns out the quick fix was pretty dirty, so I went for a solution that fully recognises that neither the widget nor the image may be square and that either dimension may be constrained at any time.  This also fixes a variety of other glitches with non-square images.

Patch here:
http://nartowicz.webspace.virginmedia.com/patch

The playlist has some of the same issues, but usually not as obvious.  The fix would go beyond just the artwork rendering in plcommon.c because the whole ddblistview assumes that the width and height of the album art cell need to be the same.

**Comment by Soukyuu** [comment]
Patch doesn't seem to want to apply on current master:
```
error: patch failed: plugins/gtkui/widgets.c:1442
error: plugins/gtkui/widgets.c: patch does not apply
```
Or manually, via patch:
```
patching file plugins/gtkui/widgets.c
Hunk #2 FAILED at 1442.
Hunk #3 FAILED at 1475.
Hunk #4 FAILED at 1693.
Hunk #5 FAILED at 2508.
Hunk #6 FAILED at 2526.
Hunk #7 succeeded at 2598 (offset -1 lines).
Hunk #8 succeeded at 2712 (offset -1 lines).
Hunk #9 succeeded at 2743 (offset -1 lines).
5 out of 9 hunks FAILED -- saving rejects to file plugins/gtkui/widgets.c.rej
```

**Comment by Lithopsian** [comment]
Sorry, my branch was three days out of date.  I'd already made the same compiler warning fixes, so no merges needed.  Try the patch now.

**Comment by Soukyuu** [comment]
Yes, it's better now. The aliasing artifacts are gone, and as long as you display the cover at 100%, it's perfectly crisp. If you're even one pixel off, though, it gets unbearably blurry... any chance of using a sharper resizer like lanczos?

**Comment by Lithopsian** [comment]
I'm not seeing this.  The disk cache file is stored at full size and the scaling into a pixbuf that fits the widget is done using gdk_pixbuf_new_from_file_at_size.  There are no controls over how it scales.  Could this depend on the GTK version?  Or the underlying jpeg library version?  I found one blurring issue, but that was way back in GTK 2.16.  Does it happen with both jpg and png files?  Is it more blurred than the older version?  Does the blurring only happen with non-square images?

There should be no cairo scaling except during the time you are resizing the widget, but if something broke and the correct size pixbuf didn't get loaded then it might remain blurred, but probably also would have aliasing artefacts.

An interesting clue might be how the default cover, the deadbeef vinyl record image, behaves.  Does it ever blur?  Or ever not blur?

**Comment by Soukyuu** [comment]
Hmm, that's weird. Now there seems to be a short time where the image is blurry after resizing it, then after letting the mouse button go, it will become rather crisp. Crisper than fb2k on wine, even :+1: 

As you said, covers on the playlist are still aliased, though.

**Comment by Lithopsian** [comment]
Good news.  This is expected behaviour.  While resizing, the image is not reloaded from disk for every pixel you move the gripper.  Whatever size image is already loaded is just resized on the fly.  When resizing from a small image to a large image it will be very blurry.  Also the algorithm itself is fast but not very accurate so even downsizing and small changes can be a bit blurry or aliased.

When you stop resizing the widget then the image is reloaded from disk at the correct resolution.  The delay is set at one second as a compromise to avoid kicking in and making the resize jerky, but still appear quite quickly.  It can take longer than one second, due to the time taken to read the file and resize it to the widget.  Large images take longer to reappear sharp.  Once you understand what is going on, it is quite easy to get the blurriness and watch it come back sharp, but in normal use it is surprisingly easy not to notice.

I don't know what to do about the playlist at the moment.  Maybe you should raise another bug specifically on that and see what people who know more about that playlist tree have to see.  Although it has all the aliasing and other issues just like the widget, it seems to me that the bigger problem is simply that the column ends up too wide for tall thin images and too tall for wide images, which is a separate issue from the image scaling itself.  That way we can close out this particular issue.

**Comment by Lithopsian** [comment]
Looking at applying the same changes to the playlist, the artwork would be vertically and horizontally centred in the tree cell.  I'm not sure that is right.  Seems like it should be at the top of the cell (ie. the group), but maybe centred horizontally?

**Comment by Alexey-Yakovenko** [comment]
It shouldn't be centered.

**Comment by Lithopsian** [comment]
Multiple album art columns.  Oh dear!  The cover info (timer, width, etc.) is carried on the listview structure, but separate copies are really needed for each album art column (and separate heights for each group if the cells are ever allowed to be non-square), or they mess eachother up during resizing.  At the moment, the only place I can see for this is the column struct itself, which seems to be abstracted behind getter and setter functions.  It would be much simple to restrict the playlist to only one album art column.

**Comment by Lithopsian** [comment]
The playlist works very nicely with non-square images now.  Tall thin images are no longer squashed into a small square region with white space all around.  They expand up to the width if the group is tall enough, but still constrained by the minimum height if it is taller than the items.

Wide (landscape) images also work, but they can leave unused whitespace.  If the image width is more than the height of the group, minimum height logic causes the group to be expanded so that a square image will fit.  For a wide non-square image, this might be unnecessary, but it isn't possible to know until the image has been loaded.  Doing this would cause the group and playlist height to change as images are loaded.  The positions of other groups might change when an image is loaded, might even change during scrolling as an image is loaded for the first time.  Although the unused whitespace isn't great, the alternative might be worse.  What do you think?  Is there a better minimum height algorithm than just height=width?

**Comment by Soukyuu** [comment]
I think that sounds fine as long as the wide cover is aligned at the top of the group (instead of having some whitespace above the upper edge). Most wide covers are only slightly wider than a square, so having some whitespace below shouldn't be that jarring. I know of no cover that has the same landscape proportions as my portrait orientation covers, anyway.

**Comment by Lithopsian** [comment]
All cover art is aligned with the top of the playlist group, or with the top of the list if it is pinned and scrolled down.  The extra white space comes below the list rows, in the pace where a square image would expand beyond the rows.  You can see much the same in the current version.  Just expend the album art column until it is wider than the playlist is tall.

**Comment by Lithopsian** [comment]
I think this can be closed now.  The quality issues with non-square artwork have been fixed, plus as many more tweaks as I think make sense.  Multiple album art columns of different sizes now also work correctly, instead of redrawing themselves every second.
