### ISSUE TITLE
Deadbeef starts muted via pulseaudio each time.

### ISSUE THREAD

**Issue by Benguin** [Alexey-Yakovenko/deadbeef#1205]
Every time I open deadbeef (either by opening a file, or by launching deadbeef and then dragging a file into it,) it starts muted in pulseaudio. I tried both the ALSA and pulseaudio playback modules and it does it with both. The OSS module refuses to play anything.

Sound plays fine once I unmute it, but it doesn't persist. I don't experience this with any other applications. I'm using Archlinux stable 64 bit, all packages up to date. Deadbeef 0.6.2.

**Comment by Alexey-Yakovenko** [comment]
This is your local pulseaudio configuration problem. Sorry, it makes no sense to have this bug open, as nobody will be able to fix it.

**Comment by kode54** [comment]
Bumping this because I managed to find it for the exact problem I was having, to indicate this issue may be because you are using communication audio, and you have the default enabled `module-role-cork` PulseAudio module loaded. It will mute audio sources on start or at any time really, if you have communications audio running. Sometimes, system error beeps trigger it too. I find it best to comment it out in `/etc/pulse/default.pa` and then on the current instance, `pacmd unload-module module-role-cork`.
