### ISSUE TITLE
Playlist column font not always initialised correctly

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1298]
Configure the column headers with a large font.
Uncheck to return to native theming.
Restart Deadbeef and open the preferences.
Font size says 10.
Click to turn on custom theming.
Font goes back to previous large size, but dialog still says 10.

**Comment by cboxdoerfer** [comment]
Just for reference: (paste from IRC)
```<c0dewiz> wander: you around? well after your font fix the status bar appears really huge to me```
```<c0dewiz> so I might revert the code on my copy back to the "bug" so I have the previous size again. menus are too large as well```

But I really don't see how this patch could interact with the status bar or menu size resp. fonts. Maybe the UI plugin was changed from GTK2 to GTK3 at some time, because most GTK3 themes (especially the default (Adwaita)) have a much bigger status bar.

**Comment by Alexey-Yakovenko** [comment]
Ditto - I can't see how this patch can do this.

**Comment by andreas--e** [comment]
Wow, even my chat msgs are now getting archived here. Didn't expect that. =D 
Yeah, in the meantime, I fiddled around a little with default font (via `LXAppearance`), making some things on my Wily bigger, some smaller. 
cboxdoerfer's fix has mainly affected the Prefs dialog indeed, which almost took 75% of m screen width first time.

Speaking of default, Alexey, __can__ I also alter the status bar size so that it only affect deadbeef and nothggn else? I also use `gnucash`, which allows the user to create a custom `.gtkrc-2.0.gnucash`. However, a quick look through the code showed me that this would still be one for the wishlist in ddb...__or_,  alternatively, consider adding an item to tweak the status bar size in Prefs. I do need to tweak this, and only for `deadbeef`; but I don't care about the way how to get there.
