### ISSUE TITLE
DND marker drawing nits

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1321]
1. With groups pinned the marker line is sometimes not drawn when it moves over the pinned title.  The sel index goes to zero instead of the actual item number, so drag motion y goes to an incorrectly small value.  The icon still indicates that a drop is possible and the item will be moved.

2. The marker line disappears at some points when moving.  The marker is never redrawn, only erased, so it is only visible if it hasn't changed location since the previous pointer position.  When a pointer move changes the cursor location, the the DND line is erased and not redrawn.  It reappears as soon as the pointer moves again.  Occurs about 5% of the time with random movements, but can be reproduced for testing just by moving the drag location very slowly until the marker disappears.

3. The marker almost disappears at the end of the playlist.  The drawing position is off-screen and only the top of the marker is visible.  Not sure how it might be fixed.  Detecting that particular location condition and nudging it up a few pixels?

**Comment by cboxdoerfer** [comment]
1. I'm not sure what you mean by that and how to reproduce it. I tried to look for some strange behavior when dragging a track and hovering/dropping it on pinned groups but didn't notice anything weird.

2. I can reproduce that. It seems this happens when the mouse cursor is exactly in the middle of a row.

3. Yes, sounds like a good solution to me.

**Comment by Lithopsian** [comment]
I edited a typo in the original explanation, not instead of now makes a big difference!  To reproduce, scroll down a few rows with the group pinned.  Select a row and drag it towards the top of the screen, but not so far that auto-scrolling starts.  When the pointer moves over the group title, the marker disappears.

**Comment by cboxdoerfer** [comment]
Ah now I get. Confirmed. I'll think of a fix.

**Comment by cboxdoerfer** [comment]
Ok, after having a closer look at that I'm not sure how to fix it or if it even needs fixing. Apparently foobar2000 with the simplaylist does exactly the same. That means: if an item is dropped on a pinned header, it gets placed exactly before the group of the pinned header and there's also no drop indicator visible, since the drop point is out of view.

Instead of placing the drop indicator at the beginning of the pinned group I tried the other way around, placing it at the end of it, this way it is always visible. But this seems also not quite right to me, since then the drop indicator makes some huge jumps, between the end of the group and the item below the pinned group title.

Any suggestions what we could do instead? Or if we should go with one of the two approaches I mentioned above?

**Comment by Lithopsian** [comment]
There's no guarantee that the end of the group is visible either ;)  Dropping on the title puts the item at the top of the group, doesn't it?  I think it would be confusing to show the marker at the end, as well as disconcerting for it to jump about.

Ideally, I think the marker would appear before the title when hovering over the title, and the same if the title is pinned.  It is ambiguous whether the item will be dropped before or after the title, until it is sorted.  It isn't the end of the world if it disappears, though.

**Comment by Lithopsian** [comment]
I tested a quick fix for item 3 by shifting the marker y coordinate by 4 pixels if it was after the last item in the list.  It makes the marker visible, but slightly overlaps the text.  Not the end of the world for something so fleeting and uncommon.  A more sophisticated solution to provide an extra 3-4 pixels for the marker to be drawn into when necessary would be complex and probably have a lot of side-effects.

I show it here on a playlist that isn't at the end of the window, for clarity, although that wouldn't happen in a final version of the code.  Also is a version shifted by only 3 pixels (one pixel of the marker is off-screen), at the end of the window.

![marker3](https://cloud.githubusercontent.com/assets/7702742/11011568/6b2ccdb6-84e1-11e5-82a8-34ada0838dda.png)
![marker](https://cloud.githubusercontent.com/assets/7702742/11011532/d50f6ed8-84e0-11e5-97f0-14089981ba75.png)

**Comment by Lithopsian** [comment]
#2 and #3 should be fixed.  #1 maybe going to stay this way?

**Comment by Alexey-Yakovenko** [comment]
Seems like this issue has been (partially?) fixed long time ago. Please create a new issue, if more work is needed.
