### ISSUE TITLE
Default equalizer in DSP chain is disabled with no obvious indication or way to enable it

### ISSUE THREAD

**Issue by Lithopsian** [Alexey-Yakovenko/deadbeef#1360]
In the preferences DSP chain configuration tab, if a SuperEQ is created automatically (new plugin, or the last SuperEQ entry has been removed) then the enabled property is initialized off.  Adjusting the equalizer has no effect on the audio. There is no indication of this in the DSP dialog or the SuperEQ configure dialog, and no way to enable it in either dialog.  A SuperEQ entry created manually using the add button is initially set to enabled and affects the audio. The equalizer can only be enabled, so far as I can tell, from the equalizer pane in the main window.  If this is made visible then there is a checkbox for enabling the equalizer.

Even if this behaviour is intentional, as a passthru mechanism, then the equalizer should at least be enabled when it is first adjusted.

**Comment by Alexey-Yakovenko** [comment]
This behaviour is intentional, because this default EQ is controlled with the specialised UI, and has its own ON/OFF button.

There's no way to disable or enable the individual nodes in the DSP chain.

Most people don't want the EQ to be enabled by default, and it also affects performance.

It's a known UI hack, and I'd like to come up with a better solution than this.

But your suggestion is not acceptable.

**Comment by Alexey-Yakovenko** [comment]
Closing because this issue is not really an issue, and there is nothing to fix.
