### ISSUE TITLE
gtkui: after clicking a sort method from "Edit -> Sort by" also column sort gets applied

### ISSUE THREAD

**Issue by cboxdoerfer** [Alexey-Yakovenko/deadbeef#1416]
Steps to reproduce:
1. Create a playlist with some tracks.
2. Sort them e.g. by track number by clicking on the track number column
3. Now go to Edit -> Sort by -> Artist

What happens in 3. is: 
The list gets first sorted by artist and then by track number.

The expected behavior in 3 is: 
remove sort indicator from column and sort the list by artist.

**Comment by Lithopsian** [comment]
Tricky.  Can we just call this a feature?

The listview (main or search or both) has no obvious way to tell that someone else has sorted the list.  Currently, all callers of plt_sort/v2 send a DB_EV_PLAYLISTCHANGED message with type DDB_PLAYLIST_CHANGE_CONTENT which looks just like a track edit, or seek, or any number of other things.  The main and search listviews now interpret playlist content changes as a trigger to re-sort by any sorted column.

The playlist modification index is bumped, but that also doesn't distinguish from a real edit.  There isn't really any direct way for sorters to call the listviews, so it seems like a new message type is needed that would announce that the playlist has changed because of an intentional sort.  Do you have any other ideas?

**Comment by Alexey-Yakovenko** [comment]
Can you guys explain how this happened? I'm sure that 0.7 branch is not affected, and this bug is a regression from the sorting refactoring, but this definitely can't be called a feature. Playlist should never ever be automatically sorted.

**Comment by Lithopsian** [comment]
I put this in deliberately.  The playlist column sort indicators that appear when you click the header button were a mess.  They would disappear randomly, or stick around when the playlist was no longer sorted that way.  See issues #1357 and #1354 for some of the problems.

I changed it so the sort indicators would persist until certain defined times such as a tab switch, or being explicitly unset, and that when the indicator was showing the playlist would stay sorted in that way.  This is apparently a little too persistent and it also needs to be cleared by explicit sorting actions.

The playlist is not automatically sorted.  It is sorted because the user clicked to sort it, and it stays sorted that way so long as the indicator is showing.  Another approach is to clear the indicator on any content change at all, also on playqueue changes.  That effectively means you might as well not have a sort indicator.  It might be improved somewhat by refining the flags that are sent out with playlistchanged messages, but in a world of custom columns and title formatting, the sort indicator just can't be relied on for long unless the list is actively kept sorted.

**Comment by Alexey-Yakovenko** [comment]
Ok.. I misunderstood what your fixes have been doing then.

You implemented sticky sorting, while what I was expecting is a fixed sort order indicator.

By design, it was supposed be this:

> Another approach is to clear the indicator on any content change at all, also on playqueue changes.

I understand that some people, including you, would like to have sticky sorting.

But this needs to be an optional feature.

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian I'm going through the sorting changes one by one, to find a way to undo the damage.

I found this place:

```
static void
remove_column (DdbListview *listview, DdbListviewColumn **c_ptr) {
    DdbListviewColumn *c = *c_ptr;
    assert (c);
    DdbListviewColumn *next = c->next;
    if (c->sort_order) { 
        listview->binding->col_sort (0, c->user_data);
    }
```

It seems like a hack to trigger redraw of the search playlist, if removed column was sorted.
Any explanation to this?

**Comment by Lithopsian** [comment]
That is primarily for the search playlist.  If a sorted column is removed then the playlist reverts to an "unsorted" state which is not just the current sort order.  The unsorted order is the same order as the main playlist.  If this is not resorted immediately when the column is removed then it will happen at some point in the future that may be confusing and disconcerting.

Calling col_sort with a sort_order of zero has no effect on the main playlist, does not resort anything and doesn't redraw the listview, although removing a column will redraw the entire listview.
