### ISSUE TITLE
JACK Output: Division by 32767 (instead of 32768)

### ISSUE THREAD

**Issue by SavantGarde** [Alexey-Yakovenko/deadbeef#1420]
Jack Bitmeter hooked up to DeaDBeeF's JACK Output shows the error described under "Mistake #1" here (last paragraph): http://devel.tlrmx.org/audio/bitmeter/

(I couldn't find a separate bug tracker for the JACK Output plugin, so I'm posting here.)

I'm using version 0.6.2 from 'debubuntu package amd64' on Ubuntu 15.10.

**Comment by Alexey-Yakovenko** [comment]
I can't seem to find the code in the jack output plugin, which divides by 32767 directly..
I guess the problem is that jack plugin respects deadbeef's volume control, so if the volume in deadbeef is not set to +0dB, the signal gets distorted, and that is misdetected as incorrect integer conversion.

**Comment by Alexey-Yakovenko** [comment]
Just looked further at the code.. I think the problem might actually be not in the jack plugin, but in deadbeef itself, because deadbeef core is what converts integer to float.

Right here: https://github.com/Alexey-Yakovenko/deadbeef/blob/master/premix.c#L159

Now I guess I need to figure out why this Bitmeter program thinks this is wrong...
max value of the int16_t is 32767, which gives us "1" when divided by 32767.

Looks correct to me?

**Comment by Alexey-Yakovenko** [comment]
32767/32768 gives us 0 on the other hand, which would be wrong.

**Comment by Alexey-Yakovenko** [comment]
ah, I think I got the point, and it starts to make sense.. if the division is done in floating point, it would give us 0.999969482421875 for the max positive value, but it will also give as the good result for the min negative value, which is -1.000030518509476 now, but would become -1.0

**Comment by Alexey-Yakovenko** [comment]
I fixed the bug, but will do some more testing in the nearest future, to make sure it works as it should.
