### ISSUE TITLE
A minor translation error.

### ISSUE THREAD

**Issue by ygyfygy** [Alexey-Yakovenko/deadbeef#1500]
https://imgur.com/HOAlU2i

Instead of "interfejsa" (near GTK2) should be "interfejsu", because it's the correst Polish translation. I'm a n00b, so I don't know how and where to fix it.

**Comment by Alexey-Yakovenko** [comment]
I can't find it, but you probably would be able to fix (or suggest a correction) on transifex, here:
https://www.transifex.com/deadbeef-player/deadbeef-player/translate/

Im' closing this bug here, because we're managing translations on transifex, and the translation issues should be reported to the transifex issue tracker.
