### ISSUE TITLE
Not visible elements: the band rewind, volume control. Used Advaita theme for GTK 3.20

### ISSUE THREAD

**Issue by midyukov-anton** [Alexey-Yakovenko/deadbeef#1547]
![2016-04-18 20-40-43](https://cloud.githubusercontent.com/assets/13087750/14606347/149f61b0-05a7-11e6-9fa1-f308ca9f9e02.png)
Not visible elements: the band rewind, volume control. Used Advaita theme for GTK 3.20. Use the same background color, and fill.
P.s.: Sorry for bad English.

**Comment by Alexey-Yakovenko** [comment]
As a workaround: it's possible to change the colors in deadbeef settings.

**Comment by Alexey-Yakovenko** [comment]
I talked with GTK devs, and they don't seem to support drawing custom widgets with themed colors, unless the application uses CSS APIs from the late GTK3 versions.

However, this approach wouldn't really solve all of the problems, because similar glitches appear with older GTK3 versions, as well as with some GTK2  themes, e.g. on default Ambience GTK2 theme in Ubuntu 12.04.

So as much as I wanted to make all of this work out of the box, I couldn't. So I simply hardcoded some sane defaults, and enabled overriding theme colors by default.

For the users who want to try the "native theming" -- please try enabling it in the settings (disabling the `override theme colors` checkboxes), and feel free to use this if it works for you.
