### ISSUE TITLE
move Clear Playlist, Edit menu --> File menu patch

### ISSUE THREAD

**Issue by mdooligan** [Alexey-Yakovenko/deadbeef#1553]
I found "Clear" in Edit menu to be unexpected behavior. I was expecting to clear the selected tracks, and surprised when it cleared the entire playlist.

I thought this item belongs more correctly with the other playlist items in the File menu. Also this patch adds menu shortcut mnemonics to all 4 playlist items in the File menu.

See attached diff.
[patch00-playlist-clear.txt](https://github.com/Alexey-Yakovenko/deadbeef/files/232027/patch00-playlist-clear.txt)

**Comment by cboxdoerfer** [comment]
Couple points:
- instead of patch files it is recommended use pull requests, this way it is a lot easier to review and comment on specific lines and also the code gets immediately compiled

- interface.c is generated by glade, so we don't modify it manually. you should use the bundled glade to modify the interface

- personally I don't think `Clear` belongs to `File` since it's not operating on files directly but it edits the playlist, so `Edit` seems to be the right place

- however I agree that "Clear" might lead to unexpected behavior, maybe we should change it to "Clear Playlist"

**Comment by mdooligan** [comment]
OK, thanks. I'll see if I can modify interface.c by changing plugins/gtkui/deadbeef.glade on a pull request.

What about the File menu mnemonics for the playlist items? Keep those?

**Comment by Alexey-Yakovenko** [comment]
It's a direct copy from fb2k. Please don't change this.
Example: http://news.softpedia.com/images/extra/WINDOWS3/large/foobar2000/foobar2000%20edit%20menu.png
