### ISSUE TITLE
Player hangs if radio stream not available

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [Alexey-Yakovenko/deadbeef#1629]
I have a long list of internet radio stations as a playlist. Sometimes a station is not available / offline. When I double click such station in the playlist to play it, the player will hang for a minute or so, before realizing, that there is nothing to do and skipping to the next list entry. An option to decrease the waiting time would be good. The player also becomes irresponsive, during that time, meaning I cannot manually switch to another station and have to wait or kill the process.

OS: Fedora 22
Player version: 0.7.2
Example URL: http://streaming207.radionomy.com:80/ZEN-FOR-YOU

I downloaded deadbeef at some point from SF, I think.

Actually I have to correct some statement: Not the whole player freezes, I only cannot switch the playlist item. I can however, still access track properties and other dialogues like preferences.

**Comment by Alexey-Yakovenko** [comment]
I believe that this can happen, but I can't accept this as a bug without repro.

Please provide a station URL or playlist which would cause the problem, then I'd reopen the bug.

**Comment by Alexey-Yakovenko** [comment]
Also, please remember to specify the exact version of the player.

If you're using an unstable release or non-release build -- please download the latest stable release, or a build from here: https://sourceforge.net/projects/deadbeef/files/travis/linux/ and make sure that the bug is still happening.

**Comment by ZelphirKaltstahl** [comment]
Added more information and an example URL.

**Comment by Alexey-Yakovenko** [comment]
I can't reproduce the problem with the URL you sent.. Probably because the stream is online.

I would really love to solve this, but without repro it's not possible.

**Comment by ZelphirKaltstahl** [comment]
I thought: "Wouldn't it work with any random URL?"
For example: http://stream.radio.com:80/blablaRandomString

So I tried, but with such manufactured URL, the player does skip to the next item in the player's playlist.

So the bug is probably the player trying to communicate with a station, which is not completely offline, but has very bad connection or something.

**Comment by Alexey-Yakovenko** [comment]
No, I'm pretty sure that this bug is something else. I know that the bug exists, because you're not the first reporting it, but it doesn't make sense to keep the bug open on github unless there's a repro.

So.. if me (or any other developer) encounters this bug, by accident, and find out what happens -- we can fix it, otherwise it will stay on github forever.

I don't like keeping such bugs open on github, because they are not helpful, and make it hard to track the rest of the bugs which are reproducible, and are fixed in orderly fashion.

**Comment by ZelphirKaltstahl** [comment]
Well it's not really a deal breaking bug, since most of the time stations are online and other players have issues with volume control of files with different types and volume (replay gain) and have issues with slow GUIs and overloaded GUIs.
I just hope some day you can find it and fix it : )

**Comment by Alexey-Yakovenko** [comment]
Yeah, I hope so too :)
