### ISSUE TITLE
Converter: "Preserve folder structure" doesn't work if all tracks are from the same directory

### ISSUE THREAD

**Issue by danpla** [Alexey-Yakovenko/deadbeef#1648]
Assume you have two directories: `album1` and `album2`, and you want to convert them in a different format. You add them in DeaDBeeF, select all tracks, open the Converter, and — among other options — choose your home dir as "Output folder", and check "Preserve folder structure".

After converting, as expected, your home directory will contain `album1` and `album2` with converted tracks. However, if you'll select tracks only from `album1` or only from `album2`, "Preserve folder structure" will have no effect — tracks will be written directly to your home directory.

DeaDBeeF 0.7.2
Xubuntu 14.04, x86_64

**Comment by Alexey-Yakovenko** [comment]
Works by design - deadbeef finds the common root of all selected tracks, and preserves the structure of remaining part of that path.

 When all of the files are in the same folder -- their "preserved" folder structure is an empty string.

This option only makes sense if more \>1 folders are selected.
