### ISSUE TITLE
 Function to "shuffle tracks" inactive in Ubuntu with the Russian language a graphical environment Unity

### ISSUE THREAD

**Issue by noisethis** [Alexey-Yakovenko/deadbeef#1706]
Function to "shuffle tracks" does not work when in Ubuntu with a graphical environment Unity system language is Russian, with English language or other graphical environment is no such problem.
![h_1485486139_6302821_68d88d7f6c](https://cloud.githubusercontent.com/assets/25566708/22628292/755eab7e-ebe2-11e6-8e38-312e7d2e2ce4.png)
![h_1485468366_4535546_8fa259ae8d](https://cloud.githubusercontent.com/assets/25566708/22628294/7697680a-ebe2-11e6-9baa-32d80211a448.png)

**Comment by Alexey-Yakovenko** [comment]
reproduced the issue in both 0.7.2 and master.

**Comment by Alexey-Yakovenko** [comment]
This is a Unity menu bar issue. I can't fix it from within deadbeef process. Sorry.

**Comment by Alexey-Yakovenko** [comment]
A workaround to this issue (and let's be fair, many other issues) is to run this:

```
sudo apt-get remove indicator-appmenu
```

then re-login.

**Comment by Alexey-Yakovenko** [comment]
The way this issue was investigated:

A simple .so was created, that replaces gtk_widget_set_sensitive with an empty function.

Then deadbeef runs like this `LD_PRELOAD=path_to.so LANGUAGE=ru deadbeef`.

It's obvious, that gtk_widget_set_sensitive stops working in deadbeef (all UI elements remain enabled, even if they were disabled from code), but in the menu it remains disabled, so assumption is that indicator-appmenu disables this menu item for some reason.
