### ISSUE TITLE
Playback slowdown in OGG&OPUS (48000Hz Sample rate)

### ISSUE THREAD

**Issue by NeoChen1024** [Alexey-Yakovenko/deadbeef#1723]

**Comment by Alexey-Yakovenko** [comment]
Please state which OS and player version you're using.

**Comment by Lithopsian** [comment]
Could be a resampling (or lack) issue.

**Comment by Alexey-Yakovenko** [comment]
Yes, it can be one of several different issues, and I need to know which player version and which OS.

**Comment by NeoChen1024** [comment]
Arch Linux (Kernel 4.10 form core)
libvorbis 1.3.5-1

**Comment by oleksiy-unity3d** [comment]
@NeoChen1024 and deadbeef version?

**Comment by NeoChen1024** [comment]
deadbeef 0.7.2-2

**Comment by oleksiy-unity3d** [comment]
@NeoChen1024 make sure you have resampler in the Preferences -> DSP, configured to use automatic samplerate, and/or Use ALSA resampling checked in the ALSA plugin settings, or use PulseAudio.. If you're using ALSA output, and don't have at least one resampling mechanism available, or have it misconfigured, e.g. by forcing resampler to specific samplerate instead of auto -- the issue you have may and will happen.

**Comment by Alexey-Yakovenko** [comment]
@NeoChen1024 make sure you have resampler in the Preferences -> DSP, configured to use automatic samplerate, and/or Use ALSA resampling checked in the ALSA plugin settings, or use PulseAudio.. If you're using ALSA output, and don't have at least one resampling mechanism available, or have it misconfigured, e.g. by forcing resampler to specific samplerate instead of auto -- the issue you have may and will happen.

**Comment by Alexey-Yakovenko** [comment]
Closing this issue because there's definitely no problem with resampling in 0.7.2, unless the player or the underlying audio subsystem is misconfigured.
