### ISSUE TITLE
Audio CDs Skip When Transitioning to Next Track

### ISSUE THREAD

**Issue by shoober420** [Alexey-Yakovenko/deadbeef#1788]
### Expected behavior
For the song to seamlessly go to the next track

### Actual behavior
There is a skip when the next song is about to start, at the one second mark.

### Steps to reproduce the behavior
Just play music with an Audio CD and it will skip at the last second for each end of a song.

This is on Arch Linux using git builds. The build is form the latest commit on May 23rd. Increasing the write speed of the drive does not help.

**Comment by Alexey-Yakovenko** [comment]
FYI: There's very low chance of getting this fixed soon, as I don't think any of the devs have CD drives in their computers anymore. Can you check if the same happens with non-CD music?

**Comment by shoober420** [comment]
This does not happen with files on the hard drive, only Audio CDs.

**Comment by Lithopsian** [comment]
I see this. In my case, it appears five seconds before the end of each track. Sounds like buffer starvation. It seems to be independent of drive read speed. I think I also get very slight skips with some other actions like opening dialogs, on a very old machine.

**Comment by Lithopsian** [comment]
When streamer_thread is loading blocks from an audio stream, streamer_read is blocked from loading them into the output plugin by a mutex. streamer_read has essentially no buffering of its own so even a short duration block starves the output plugin of audio samples. The streamer_thread mutex lock contains the audio plugin IO which can take an extremely long time by mutex standards. The cdda plugin IO can be particularly slow, and especially for seeks and the start of new tracks. The audio stutters after manual seeks, but people might not consider it a problem. During track changes, the audio stutter is more obvious. Occasionally, the audio stutters during other computer actions or just randomly.

Removing the mutex locks from streamer_read solves the problem completely, but presumably carries a risk of crashes. I hacked up some buffering and a trylock system and this helped but it seems to need a substantial buffer to completely eliminate the problem - I'm not sure how long IO might possibly take, and in really unlucky cases streamer_read can repeatedly hit different streamer_thread locks instead of one long lock. The real solution would seem to be to do the audio plugin IO outside the mutex lock, but I haven't tried it because it isn't a simple change with the mutexes in streamer.c and the plugin calls in streamreader.c.

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian thanks for investigating this. It was not intentional to block all IO while data is being streamed. Should be fairly simple to fix on my side. I'll have a look today.

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian @shoober420  I just pushed commit e45a85d3831105c9195bb3a125b394a6296573e5, which doesn't block while reading from stream. Please let me know if anything has changed for better.

**Comment by Lithopsian** [comment]
I can't get it to glitch at all now.

**Comment by Alexey-Yakovenko** [comment]
Great. Thanks for the help, closing.

**Comment by shoober420** [comment]
This fixed it for me as well. Thank you so much Alexey
