### ISSUE TITLE
Will there be a 0.7.3 or 0.8 version of DeaDBeeF?

### ISSUE THREAD

**Issue by JulianLai** [Alexey-Yakovenko/deadbeef#1792]

**Comment by Alexey-Yakovenko** [comment]
Yes, the next will be 0.8.

The remaining work for it, aside from testing and polishing the existing code:

* Fix all regressions caused by the streamer refactoring (various stuttering bugs, buffering indication, cutting off last few seconds at last track, various lock-ups in alsa/pulse, etc)
* Port Replaygain Scanner UI to GTK / Linux

That's still quite large amount of work, so no timeline yet.
I'm actively working on the first part.
