### ISSUE TITLE
Плагин V2M

### ISSUE THREAD

**Issue by alexeysvrv** [Alexey-Yakovenko/deadbeef#1832]
Здравствуй Алексей. Предлагаю выключить по умолчанию сборку с плагином V2M(синтезатор).
Он будет использоваться малой аудиторией. Deadbeef позиционируется как проигрыватель.

**Comment by Alexey-Yakovenko** [comment]
As a rule of thumb, all modules which are stable and usable are enabled by default, as long as build dependencies are met.

When the modules break the player, or degrade the user experience -- we can start discussion about disabling them.

And I don't really get your argument that V2M is a synthesizer. All audio decoders/players are synthesizers in one way or another.

I know that this answer will most likely not satisfy you, so you should know that the issue has been closed as invalid, because V2M plugin is not included in the Linux builds at all, and therefore there's no way to disable it.

**Comment by alexeysvrv** [comment]
@Alexey-Yakovenko Спасибо за ответ и объяснение
