### ISSUE TITLE
[android] Lock screen buttons

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#899]
Original [issue 997](https://code.google.com/p/ddb/issues/detail?id=997) created by Alexey-Yakovenko on 2013-11-10T18:50:53.000Z:

It would be nice feature to include some control buttons on android lock screen

**Comment by stronny** [comment]
in general, deadbeef should implement [RemoteControlClient](https://developer.android.com/reference/android/media/RemoteControlClient.html) interface so that the lockscreen can pick up track info and send media buttons back to player. just stumbled upon this missing feature while putting together a pebble music control.

**Comment by Alexey-Yakovenko** [comment]
This is fixed in DDB2.
