### ISSUE TITLE
[android] Bluetooth query support

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [Alexey-Yakovenko/deadbeef#991]
Original [issue 1089](https://code.google.com/p/ddb/issues/detail?id=1089) created by Alexey-Yakovenko on 2014-04-06T20:24:28.000Z:

<b>What steps will reproduce the problem?</b>
1. Connect to a car media system or other device that supports displaying &quot;now playing&quot; and/or library browsing
2. Nothing shows up, or worse, the text relating to the last played item in the stock audio player shows up.

<b>What is the expected output? What do you see instead?</b>
The car's queries return the currently playing song in deadbeef.

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>
1.24, pro version.  Moto X, Android 4.4.2.

<b>How did you install the product?</b>
Android market.

<b>Please provide any additional information below.</b>
Library browsing support would be nice, but now playing text is way more important.

**Comment by Malbeth81** [comment]
I would also love this to be added, I switched from the default Android player (and even purchased Deadbeef Pro) because it offers album shuffling (a feature most of the mobile apps lack) and it's been great but when I use it in my car the song information no longer shows up despite the on-steering controls working fine, the song information is all that's missing for this to work perfectly!

**Comment by Alexey-Yakovenko** [comment]
DDB2 supports sending nowplaying information to compatible bluetooth devices
